### ISSUE TITLE
add Caching

### ISSUE THREAD

**Issue by ellispenning** [openearth/vegetatiemonitor#109]
fetch image times based on region/zoom level, configure caching ee summit notes

Cron updating of feature collection in EE for S2 image ids, cloud score, etc.

**Comment by gena** [comment]
To implement this, we will have to make requests less random by making polygons more discrete, like use XYZ tile boundaries instead of the actual polygons to query times. Caching can be implemented on App Engine side as explained in slide 22 here: https://docs.google.com/presentation/d/1AVJJc3WftZf9wdpId0DvY5u-vYmxWl8x2AwWmzErfA4/edit#slide=id.g3c39bc54de_0_687

**Comment by gena** [comment]
Duplicate to #145
